analytics: "G-VCVX2DGPPN"
collections:
  press:
    output: true
    permalink: /:collection/:name
defaults:
  - scope:
      path: ""
      type: press
    values:
      layout: press
description: A state government initiative, Cal-ITP is making riding by rail and bus simpler and more cost-effective—for California transit providers and riders.
domain: www.calitp.org
google_fonts: "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&family=Raleway:wght@700&display=swap"
source: ./src
timezone: America/Los_Angeles
title: "Cal-ITP: California Integrated Travel Project"
url: "https://www.calitp.org"
